### ISSUE TITLE
Allow links to relative paths

### ISSUE THREAD

**Issue by benjaminwd** [scallywag/org-board#14]
It would be nice if org-board were able to create links to relative paths. Or at least use the ~ home folder convention. I use both MacOS which uses /Users/<username> and Linux which uses /home/<username>.

**Comment by scallywag** [comment]
I would like to support links to relative file names, but the 
"org-attach" package itself only seems to support absolute file names.  
See, for example, the "org-attach-dir" function, which makes sure to 
only return canonicalized file names (by using "expand-file-name").  
That said, manually replacing "/Users/$USER" with "~", in an org-board 
link, then running "org-board-open", still seems to work fine.

**Comment by stardiviner** [comment]
If `org-attach` can be adapted to use relative path, that will be great, don't know whether it is possible.

**Comment by stardiviner** [comment]
Org-attach can use relative path now. It's controled by option `org-link-file-path-type`. Set it to `'relative` to use relative file path.
