### ISSUE TITLE
More descriptive name?

### ISSUE THREAD

**Issue by alphapapa** [scallywag/org-board#4]
Hi Charles,

I was thinking, org-board doesn't seem like a very descriptive name.  There are so many org-related packages now, and it's hard for me to keep track of them all and remember which one does what, especially when I haven't integrated it into my workflow yet.  What if this were renamed to something like `org-web-archive`?  Just an idea.  :)

**Comment by scallywag** [comment]
You're right, at the moment this package is mainly a web archiver. But there are a few changes in the pipeline that will hopefully improve it and turn it into something better: maybe something a bit like a "blackboard" for the web, where you can annotate the contents of archives either in-place (in Emacs, in the case of simple text pages), or alternatively in the browser using some kind of automatically injected JavaScript. The "board" name is a bit vague for now, but will probably end up sticking (I hope!).

**Comment by alphapapa** [comment]
Annotating pages sounds very interesting.  Are you thinking of something like the ScrapBook extension for Firefox?

**Comment by scallywag** [comment]
Yes, but without the Firefox dependency. :D

**Comment by alphapapa** [comment]
That would be great!  I've used ScrapBook for years, but sometimes I feel like the pages I save in it are prisoners within its walls (mostly because Firefox is so slow to start).  I've taken to saving text articles in Org format sometimes, but that is only appropriate for some articles.
